### ISSUE TITLE
Trying to ingest the full log eventually fails

### ISSUE THREAD

**Issue by clintmiller** [dubdromic/cod2stat#1]
```
goroutine 1 [running]:
main.panicIfErr(0x13c5b40, 0xc420118000)
	/Users/clintmiller/Code/go/src/github.com/dubdromic/cod2stat/util.go:5 +0x4a
main.insertGameRows(0xc420098140, 0xc420016330, 0x24, 0x0, 0x0, 0x0)
	/Users/clintmiller/Code/go/src/github.com/dubdromic/cod2stat/queries.go:32 +0x7a2
main.main()
	/Users/clintmiller/Code/go/src/github.com/dubdromic/cod2stat/json_to_database.go:30 +0x136
panic: pq: nextval: reached maximum value of sequence "casualties_id_seq" (2147483647)
```

How do you tell PG to use something other than a signed 32-bit integer for sequence numbering?

**Comment by dubdromic** [comment]
`bigserial`! Fixed on `master`.
